### ISSUE TITLE
Problems with make file

### ISSUE THREAD

**Issue by nbetrapa** [rdpstaff/classifier#15]
I have been trying to make the RDPtools, however I keep running into make issues. I am following the instructions on the README file, I am making using super user prevligies (SU). Below is the output. Kindly help me figure this out. 

ant -f Clustering/build.xml jar
Buildfile: /opt/RDPTools/Clustering/build.xml

download-ivy:
      [get] Getting: http://repo2.maven.org/maven2/org/apache/ivy/ivy/2.1.0-rc2/ivy-2.1.0-rc2.jar
      [get] To: /root/.ant/lib/ivy.jar
      [get] Not modified - so not downloaded

init-ivy:

resolve:
[ivy:retrieve] :: Ivy 2.1.0-rc2 - 20090704004254 :: http://ant.apache.org/ivy/ ::
[ivy:retrieve] :: loading settings :: url = jar:file:/root/.ant/lib/ivy.jar!/org/apache/ivy/core/settings/ivysettings.xml
[ivy:retrieve] :: resolving dependencies :: edu.cme.rdp#clustering;working@mbac.gmu.edu
[ivy:retrieve] 	confs: [default]
[ivy:retrieve] 	found com.sun.xml.bind#jaxb-impl;2.2.7 in public
[ivy:retrieve] 	found com.sun.xml.bind#jaxb-core;2.2.7 in public
[ivy:retrieve] 	found javax.xml.bind#jaxb-api;2.2.7 in public
[ivy:retrieve] 	found com.sun.istack#istack-commons-runtime;2.16 in public
[ivy:retrieve] 	found com.sun.xml.fastinfoset#FastInfoset;1.2.12 in public
[ivy:retrieve] 	found javax.xml.bind#jsr173_api;1.0 in public
[ivy:retrieve] 	found commons-cli#commons-cli;1.2 in public
[ivy:retrieve] 	found junit#junit;4.8.2 in public
[ivy:retrieve] 	found commons-codec#commons-codec;1.8 in public
[ivy:retrieve] 	found commons-io#commons-io;2.4 in public
[ivy:retrieve] :: resolution report :: resolve 253ms :: artifacts dl 21ms
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   10  |   0   |   0   |   0   ||   20  |   0   |
	---------------------------------------------------------------------
[ivy:retrieve] :: retrieving :: edu.cme.rdp#clustering
[ivy:retrieve] 	confs: [default]
[ivy:retrieve] 	0 artifacts copied, 20 already retrieved (0kB/10ms)

-pre-init:

-init-private:

-init-user:

-init-project:

-init-macrodef-property:

-do-init:

-post-init:

-init-check:

-init-ap-cmdline-properties:

-init-macrodef-javac-with-processors:

-init-macrodef-javac-without-processors:

-init-macrodef-javac:

-init-macrodef-test-impl:

-init-macrodef-junit-init:

-init-macrodef-junit-single:

-init-test-properties:

-init-macrodef-junit-batch:

-init-macrodef-junit:

-init-macrodef-junit-impl:
Trying to override old definition of task http://www.netbeans.org/ns/j2se-project/3:test-impl

-init-macrodef-testng:

-init-macrodef-testng-impl:

-init-macrodef-test:

-init-macrodef-junit-debug:

-init-macrodef-junit-debug-batch:

-init-macrodef-junit-debug-impl:

-init-macrodef-test-debug-junit:

-init-macrodef-testng-debug:

-init-macrodef-testng-debug-impl:

-init-macrodef-test-debug-testng:

-init-macrodef-test-debug:

-init-debug-args:

-init-macrodef-nbjpda:

-init-macrodef-debug:

-init-macrodef-java:

-init-presetdef-jar:

-init-ap-cmdline-supported:

-init-ap-cmdline:

init:

-deps-jar-init:
   [delete] Deleting: /opt/RDPTools/Clustering/build/built-jar.properties

deps-jar:

-warn-already-built-jar:
[propertyfile] Updating property file: /opt/RDPTools/Clustering/build/built-jar.properties

-check-call-dep:

-maybe-call-dep:

download-ivy:
      [get] Getting: http://repo2.maven.org/maven2/org/apache/ivy/ivy/2.1.0-rc2/ivy-2.1.0-rc2.jar
      [get] To: /root/.ant/lib/ivy.jar
      [get] Not modified - so not downloaded

init-ivy:

resolve:
[ivy:retrieve] :: loading settings :: url = jar:file:/root/.ant/lib/ivy.jar!/org/apache/ivy/core/settings/ivysettings.xml
[ivy:retrieve] :: resolving dependencies :: edu.cme.rdp#AlignmentTools;working@mbac.gmu.edu
[ivy:retrieve] 	confs: [default]
[ivy:retrieve] 	found commons-lang#commons-lang;2.6 in public
[ivy:retrieve] 	found commons-cli#commons-cli;1.2 in public
[ivy:retrieve] :: resolution report :: resolve 31ms :: artifacts dl 4ms
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   2   |   0   |   0   |   0   ||   6   |   0   |
	---------------------------------------------------------------------
[ivy:retrieve] :: retrieving :: edu.cme.rdp#AlignmentTools
[ivy:retrieve] 	confs: [default]
[ivy:retrieve] 	0 artifacts copied, 6 already retrieved (0kB/3ms)

-pre-init:

-init-private:

-init-user:

-init-project:

-init-macrodef-property:

-do-init:

-post-init:

-init-check:

-init-ap-cmdline-properties:

-init-macrodef-javac-with-processors:

-init-macrodef-javac-without-processors:
Trying to override old definition of task http://www.netbeans.org/ns/j2se-project/3:javac

-init-macrodef-javac:
Trying to override old definition of task http://www.netbeans.org/ns/j2se-project/3:depend

-init-macrodef-test-impl:
Trying to override old definition of task http://www.netbeans.org/ns/j2se-project/3:test-impl

-init-macrodef-junit-init:

-init-macrodef-junit-single:

-init-test-properties:

-init-macrodef-junit-batch:

-init-macrodef-junit:

-init-macrodef-junit-impl:

-init-macrodef-testng:

-init-macrodef-testng-impl:

-init-macrodef-test:

-init-macrodef-junit-debug:

-init-macrodef-junit-debug-batch:

-init-macrodef-junit-debug-impl:

-init-macrodef-test-debug-junit:

-init-macrodef-testng-debug:

-init-macrodef-testng-debug-impl:

-init-macrodef-test-debug-testng:

-init-macrodef-test-debug:

-init-debug-args:

-init-macrodef-nbjpda:
Trying to override old definition of task http://www.netbeans.org/ns/j2se-project/1:nbjpdastart

-init-macrodef-debug:
Trying to override old definition of task http://www.netbeans.org/ns/j2se-project/3:debug

-init-macrodef-java:
Trying to override old definition of task http://www.netbeans.org/ns/j2se-project/1:java

-init-presetdef-jar:

-init-ap-cmdline-supported:

-init-ap-cmdline:

init:

-deps-jar-init:

deps-jar:

-warn-already-built-jar:
[propertyfile] Updating property file: /opt/RDPTools/Clustering/build/built-jar.properties

-check-call-dep:

-maybe-call-dep:

download-ivy:
      [get] Getting: http://repo2.maven.org/maven2/org/apache/ivy/ivy/2.1.0-rc2/ivy-2.1.0-rc2.jar
      [get] To: /root/.ant/lib/ivy.jar
      [get] Not modified - so not downloaded

init-ivy:

resolve:
[ivy:retrieve] :: loading settings :: url = jar:file:/root/.ant/lib/ivy.jar!/org/apache/ivy/core/settings/ivysettings.xml
[ivy:retrieve] :: resolving dependencies :: edu.cme.rdp#ReadSeq;working@mbac.gmu.edu
[ivy:retrieve] 	confs: [default]
[ivy:retrieve] 	found commons-lang#commons-lang;2.6 in public
[ivy:retrieve] 	found commons-cli#commons-cli;1.2 in public
[ivy:retrieve] 	found commons-io#commons-io;2.4 in public
[ivy:retrieve] :: resolution report :: resolve 39ms :: artifacts dl 6ms
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   3   |   0   |   0   |   0   ||   9   |   0   |
	---------------------------------------------------------------------
[ivy:retrieve] :: retrieving :: edu.cme.rdp#ReadSeq
[ivy:retrieve] 	confs: [default]
[ivy:retrieve] 	0 artifacts copied, 9 already retrieved (0kB/3ms)

-pre-init:

-init-private:

-init-user:

-init-project:

-init-macrodef-property:

-do-init:

-post-init:

-init-check:

-init-ap-cmdline-properties:

-init-macrodef-javac-with-processors:

-init-macrodef-javac-without-processors:
Trying to override old definition of task http://www.netbeans.org/ns/j2se-project/3:javac

-init-macrodef-javac:
Trying to override old definition of task http://www.netbeans.org/ns/j2se-project/3:depend

-init-macrodef-test-impl:

-init-macrodef-junit-init:

-init-macrodef-junit-single:

-init-test-properties:

-init-macrodef-junit-batch:

-init-macrodef-junit:

-init-macrodef-junit-impl:

-init-macrodef-testng:

-init-macrodef-testng-impl:

-init-macrodef-test:

-init-macrodef-junit-debug:

-init-macrodef-junit-debug-batch:

-init-macrodef-junit-debug-impl:

-init-macrodef-test-debug-junit:

-init-macrodef-testng-debug:

-init-macrodef-testng-debug-impl:

-init-macrodef-test-debug-testng:

-init-macrodef-test-debug:

-init-debug-args:

-init-macrodef-nbjpda:
Trying to override old definition of task http://www.netbeans.org/ns/j2se-project/1:nbjpdastart

-init-macrodef-debug:
Trying to override old definition of task http://www.netbeans.org/ns/j2se-project/3:debug

-init-macrodef-java:
Trying to override old definition of task http://www.netbeans.org/ns/j2se-project/1:java

-init-presetdef-jar:

-init-ap-cmdline-supported:

-init-ap-cmdline:

init:

-deps-jar-init:

deps-jar:

-warn-already-built-jar:
[propertyfile] Updating property file: /opt/RDPTools/Clustering/build/built-jar.properties

-check-automatic-build:

-clean-after-automatic-build:

-verify-automatic-build:

-pre-pre-compile:

-pre-compile:

-copy-persistence-xml:

-compile-depend:

-do-compile:

-post-compile:

compile:

-pre-jar:

-post-jar:

jar:
     [echo] To run this application from the command line without Ant, try:
     [echo] java -jar "/opt/RDPTools/ReadSeq/dist/ReadSeq.jar"

-check-automatic-build:

-clean-after-automatic-build:

-verify-automatic-build:

-pre-pre-compile:

-pre-compile:

-copy-persistence-xml:

-compile-depend:

-do-compile:

-post-compile:

compile:

-pre-jar:

-post-jar:

jar:
     [echo] To run this application from the command line without Ant, try:
     [echo] java -jar "/opt/RDPTools/AlignmentTools/dist/AlignmentTools.jar"

-check-call-dep:

-maybe-call-dep:

-check-call-dep:

-maybe-call-dep:

download-ivy:
      [get] Getting: http://repo2.maven.org/maven2/org/apache/ivy/ivy/2.1.0-rc2/ivy-2.1.0-rc2.jar
      [get] To: /root/.ant/lib/ivy.jar
      [get] Not modified - so not downloaded

init-ivy:

resolve:
[ivy:retrieve] :: loading settings :: url = jar:file:/root/.ant/lib/ivy.jar!/org/apache/ivy/core/settings/ivysettings.xml
[ivy:retrieve] :: resolving dependencies :: edu.cme.rdp#SeqFilters;working@mbac.gmu.edu
[ivy:retrieve] 	confs: [default]
[ivy:retrieve] 	found commons-lang#commons-lang;2.6 in public
[ivy:retrieve] 	found commons-cli#commons-cli;1.2 in public
[ivy:retrieve] 	found jfree#jfreechart;1.0.13 in public
[ivy:retrieve] 	found jfree#jcommon;1.0.16 in public
[ivy:retrieve] :: resolution report :: resolve 46ms :: artifacts dl 6ms
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   4   |   0   |   0   |   0   ||   10  |   0   |
	---------------------------------------------------------------------
[ivy:retrieve] :: retrieving :: edu.cme.rdp#SeqFilters
[ivy:retrieve] 	confs: [default]
[ivy:retrieve] 	0 artifacts copied, 10 already retrieved (0kB/3ms)

-pre-init:

-init-private:

-init-user:

-init-project:

-init-macrodef-property:

-do-init:

-post-init:

-init-check:

-init-ap-cmdline-properties:

-init-macrodef-javac-with-processors:

-init-macrodef-javac-without-processors:
Trying to override old definition of task http://www.netbeans.org/ns/j2se-project/3:javac

-init-macrodef-javac:
Trying to override old definition of task http://www.netbeans.org/ns/j2se-project/3:depend

-init-macrodef-test-impl:
Trying to override old definition of task http://www.netbeans.org/ns/j2se-project/3:test-impl

-init-macrodef-junit-init:

-init-macrodef-junit-single:

-init-test-properties:

-init-macrodef-junit-batch:

-init-macrodef-junit:

-init-macrodef-junit-impl:

-init-macrodef-testng:

-init-macrodef-testng-impl:

-init-macrodef-test:

-init-macrodef-junit-debug:

-init-macrodef-junit-debug-batch:

-init-macrodef-junit-debug-impl:

-init-macrodef-test-debug-junit:

-init-macrodef-testng-debug:

-init-macrodef-testng-debug-impl:

-init-macrodef-test-debug-testng:

-init-macrodef-test-debug:

-init-debug-args:

-init-macrodef-nbjpda:
Trying to override old definition of task http://www.netbeans.org/ns/j2se-project/1:nbjpdastart

-init-macrodef-debug:
Trying to override old definition of task http://www.netbeans.org/ns/j2se-project/3:debug

-init-macrodef-java:
Trying to override old definition of task http://www.netbeans.org/ns/j2se-project/1:java

-init-presetdef-jar:

-init-ap-cmdline-supported:

-init-ap-cmdline:

init:

-deps-jar-init:

deps-jar:

-warn-already-built-jar:
[propertyfile] Updating property file: /opt/RDPTools/Clustering/build/built-jar.properties

-check-call-dep:

-maybe-call-dep:

download-ivy:
      [get] Getting: http://repo2.maven.org/maven2/org/apache/ivy/ivy/2.1.0-rc2/ivy-2.1.0-rc2.jar
      [get] To: /root/.ant/lib/ivy.jar
      [get] Not modified - so not downloaded

init-ivy:

resolve:
[ivy:retrieve] :: loading settings :: url = jar:file:/root/.ant/lib/ivy.jar!/org/apache/ivy/core/settings/ivysettings.xml
[ivy:retrieve] :: resolving dependencies :: edu.cme.rdp#ProbeMatch;working@mbac.gmu.edu
[ivy:retrieve] 	confs: [default]
[ivy:retrieve] 	found commons-lang#commons-lang;2.6 in public
[ivy:retrieve] 	found commons-cli#commons-cli;1.2 in public
[ivy:retrieve] 	found junit#junit;4.8.2 in public
[ivy:retrieve] :: resolution report :: resolve 32ms :: artifacts dl 5ms
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   3   |   0   |   0   |   0   ||   9   |   0   |
	---------------------------------------------------------------------
[ivy:retrieve] :: retrieving :: edu.cme.rdp#ProbeMatch
[ivy:retrieve] 	confs: [default]
[ivy:retrieve] 	0 artifacts copied, 9 already retrieved (0kB/3ms)

-pre-init:

-init-private:

-init-user:

-init-project:

-init-macrodef-property:

-do-init:

-post-init:

-init-check:

-init-ap-cmdline-properties:

-init-macrodef-javac-with-processors:

-init-macrodef-javac-without-processors:
Trying to override old definition of task http://www.netbeans.org/ns/j2se-project/3:javac

-init-macrodef-javac:
Trying to override old definition of task http://www.netbeans.org/ns/j2se-project/3:depend

-init-macrodef-test-impl:

-init-macrodef-junit-init:

-init-macrodef-junit-single:

-init-test-properties:

-init-macrodef-junit-batch:

-init-macrodef-junit:

-init-macrodef-junit-impl:
Trying to override old definition of task http://www.netbeans.org/ns/j2se-project/3:test-impl

-init-macrodef-testng:

-init-macrodef-testng-impl:

-init-macrodef-test:

-init-macrodef-junit-debug:

-init-macrodef-junit-debug-batch:

-init-macrodef-junit-debug-impl:

-init-macrodef-test-debug-junit:
Trying to override old definition of task http://www.netbeans.org/ns/j2se-project/3:test-debug

-init-macrodef-testng-debug:

-init-macrodef-testng-debug-impl:

-init-macrodef-test-debug-testng:

-init-macrodef-test-debug:

-init-debug-args:

-init-macrodef-nbjpda:
Trying to override old definition of task http://www.netbeans.org/ns/j2se-project/1:nbjpdastart

-init-macrodef-debug:
Trying to override old definition of task http://www.netbeans.org/ns/j2se-project/3:debug

-init-macrodef-java:
Trying to override old definition of task http://www.netbeans.org/ns/j2se-project/1:java

-init-presetdef-jar:

-init-ap-cmdline-supported:

-init-ap-cmdline:

init:

-deps-jar-init:

deps-jar:

-warn-already-built-jar:
[propertyfile] Updating property file: /opt/RDPTools/Clustering/build/built-jar.properties

-check-call-dep:

-maybe-call-dep:

-check-call-dep:

-maybe-call-dep:

-check-automatic-build:

-clean-after-automatic-build:

-verify-automatic-build:

-pre-pre-compile:

-pre-compile:

-copy-persistence-xml:

-compile-depend:

-do-compile:

-post-compile:

compile:

-pre-jar:

-post-jar:

jar:
     [echo] To run this application from the command line without Ant, try:
     [echo] java -jar "/opt/RDPTools/ProbeMatch/dist/ProbeMatch.jar"

-check-call-dep:

-maybe-call-dep:

-check-automatic-build:

-clean-after-automatic-build:

-verify-automatic-build:

-pre-pre-compile:

-pre-compile:

-copy-persistence-xml:

-compile-depend:

-do-compile:

-post-compile:

compile:

-pre-jar:

-post-jar:

jar:
     [echo] To run this application from the command line without Ant, try:
     [echo] java -jar "/opt/RDPTools/SeqFilters/dist/SeqFilters.jar"

-check-call-dep:

-maybe-call-dep:

-check-call-dep:

-maybe-call-dep:

-check-automatic-build:

-clean-after-automatic-build:

-verify-automatic-build:

-pre-pre-compile:

-pre-compile:

-copy-persistence-xml:

-compile-depend:

-do-compile:
    [javac] Compiling 72 source files to /opt/RDPTools/Clustering/build/classes
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.5
    [javac] /opt/RDPTools/Clustering/src/edu/msu/cme/pyro/cluster/ClusterReplay.java:26: error: cannot find symbol
    [javac] import edu.msu.cme.rdp.taxatree.Taxon;
    [javac]                                ^
    [javac]   symbol:   class Taxon
    [javac]   location: package edu.msu.cme.rdp.taxatree
    [javac] /opt/RDPTools/Clustering/src/edu/msu/cme/pyro/cluster/ClusterReplay.java:27: error: cannot find symbol
    [javac] import edu.msu.cme.rdp.taxatree.TaxonHolder;
    [javac]                                ^
    [javac]   symbol:   class TaxonHolder
    [javac]   location: package edu.msu.cme.rdp.taxatree
    [javac] /opt/RDPTools/Clustering/src/edu/msu/cme/rdp/taxatree/TreeBuilder.java:22: error: package edu.msu.cme.rdp.taxatree.utils does not exist
    [javac] import edu.msu.cme.rdp.taxatree.utils.NewickPrintVisitor;
    [javac]                                      ^
    [javac] /opt/RDPTools/Clustering/src/edu/msu/cme/rdp/taxatree/TreeBuilder.java:23: error: package edu.msu.cme.rdp.taxatree.utils.NewickPrintVisitor does not exist
    [javac] import edu.msu.cme.rdp.taxatree.utils.NewickPrintVisitor.NewickDistanceFactory;
    [javac]                                                         ^
    [javac] /opt/RDPTools/Clustering/src/edu/msu/cme/rdp/taxatree/TreeBuilder.java:50: error: cannot find symbol
    [javac]         TaxonHolder lastMerged = null;
    [javac]         ^
    [javac]   symbol:   class TaxonHolder
    [javac]   location: class TreeBuilder
    [javac] /opt/RDPTools/Clustering/src/edu/msu/cme/rdp/taxatree/TreeBuilder.java:53: error: cannot find symbol
    [javac]         Map<Integer, TaxonHolder> taxonMap = new HashMap();
    [javac]                      ^
    [javac]   symbol:   class TaxonHolder
    [javac]   location: class TreeBuilder
    [javac] /opt/RDPTools/Clustering/src/edu/msu/cme/rdp/taxatree/TreeBuilder.java:60: error: cannot find symbol
    [javac]                     TaxonHolder<Taxon> holder;
    [javac]                     ^
    [javac]   symbol:   class TaxonHolder
    [javac]   location: class TreeBuilder
    [javac] /opt/RDPTools/Clustering/src/edu/msu/cme/rdp/taxatree/TreeBuilder.java:60: error: cannot find symbol
    [javac]                     TaxonHolder<Taxon> holder;
    [javac]                                 ^
    [javac]   symbol:   class Taxon
    [javac]   location: class TreeBuilder
    [javac] /opt/RDPTools/Clustering/src/edu/msu/cme/rdp/taxatree/TreeBuilder.java:64: error: cannot find symbol
    [javac]                         holder = new TaxonHolder(new Taxon(taxid++, seqids.get(0), ""));
    [javac]                                      ^
    [javac]   symbol:   class TaxonHolder
    [javac]   location: class TreeBuilder
    [javac] /opt/RDPTools/Clustering/src/edu/msu/cme/rdp/taxatree/TreeBuilder.java:64: error: cannot find symbol
    [javac]                         holder = new TaxonHolder(new Taxon(taxid++, seqids.get(0), ""));
    [javac]                                                      ^
    [javac]   symbol:   class Taxon
    [javac]   location: class TreeBuilder
    [javac] /opt/RDPTools/Clustering/src/edu/msu/cme/rdp/taxatree/TreeBuilder.java:66: error: cannot find symbol
    [javac]                         holder = new TaxonHolder(new Taxon(taxid++, "", ""));
    [javac]                                      ^
    [javac]   symbol:   class TaxonHolder
    [javac]   location: class TreeBuilder
    [javac] /opt/RDPTools/Clustering/src/edu/msu/cme/rdp/taxatree/TreeBuilder.java:66: error: cannot find symbol
    [javac]                         holder = new TaxonHolder(new Taxon(taxid++, "", ""));
    [javac]                                                      ^
    [javac]   symbol:   class Taxon
    [javac]   location: class TreeBuilder
    [javac] /opt/RDPTools/Clustering/src/edu/msu/cme/rdp/taxatree/TreeBuilder.java:70: error: cannot find symbol
    [javac]                             TaxonHolder th = new TaxonHolder(new Taxon(id, seqid, ""));
    [javac]                             ^
    [javac]   symbol:   class TaxonHolder
    [javac]   location: class TreeBuilder
    [javac] /opt/RDPTools/Clustering/src/edu/msu/cme/rdp/taxatree/TreeBuilder.java:70: error: cannot find symbol
    [javac]                             TaxonHolder th = new TaxonHolder(new Taxon(id, seqid, ""));
    [javac]                                                  ^
    [javac]   symbol:   class TaxonHolder
    [javac]   location: class TreeBuilder
    [javac] /opt/RDPTools/Clustering/src/edu/msu/cme/rdp/taxatree/TreeBuilder.java:70: error: cannot find symbol
    [javac]                             TaxonHolder th = new TaxonHolder(new Taxon(id, seqid, ""));
    [javac]                                                                  ^
    [javac]   symbol:   class Taxon
    [javac]   location: class TreeBuilder
    [javac] /opt/RDPTools/Clustering/src/edu/msu/cme/rdp/taxatree/TreeBuilder.java:84: error: cannot find symbol
    [javac]                     TaxonHolder holder = new TaxonHolder(new Taxon(taxid++, "", ""));
    [javac]                     ^
    [javac]   symbol:   class TaxonHolder
    [javac]   location: class TreeBuilder
    [javac] /opt/RDPTools/Clustering/src/edu/msu/cme/rdp/taxatree/TreeBuilder.java:84: error: cannot find symbol
    [javac]                     TaxonHolder holder = new TaxonHolder(new Taxon(taxid++, "", ""));
    [javac]                                              ^
    [javac]   symbol:   class TaxonHolder
    [javac]   location: class TreeBuilder
    [javac] /opt/RDPTools/Clustering/src/edu/msu/cme/rdp/taxatree/TreeBuilder.java:84: error: cannot find symbol
    [javac]                     TaxonHolder holder = new TaxonHolder(new Taxon(taxid++, "", ""));
    [javac]                                                              ^
    [javac]   symbol:   class Taxon
    [javac]   location: class TreeBuilder
    [javac] /opt/RDPTools/Clustering/src/edu/msu/cme/rdp/taxatree/TreeBuilder.java:106: error: cannot find symbol
    [javac]         NewickPrintVisitor visitor = new NewickPrintVisitor(newickTreeOut, false, new NewickDistanceFactory() {
    [javac]         ^
    [javac]   symbol:   class NewickPrintVisitor
    [javac]   location: class TreeBuilder
    [javac] /opt/RDPTools/Clustering/src/edu/msu/cme/rdp/taxatree/TreeBuilder.java:106: error: cannot find symbol
    [javac]         NewickPrintVisitor visitor = new NewickPrintVisitor(newickTreeOut, false, new NewickDistanceFactory() {
    [javac]                                          ^
    [javac]   symbol:   class NewickPrintVisitor
    [javac]   location: class TreeBuilder
    [javac] /opt/RDPTools/Clustering/src/edu/msu/cme/rdp/taxatree/TreeBuilder.java:106: error: cannot find symbol
    [javac]         NewickPrintVisitor visitor = new NewickPrintVisitor(newickTreeOut, false, new NewickDistanceFactory() {
    [javac]                                                                                       ^
    [javac]   symbol:   class NewickDistanceFactory
    [javac]   location: class TreeBuilder
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 21 errors
    [javac] 1 warning

BUILD FAILED
/opt/RDPTools/Clustering/nbproject/build-impl.xml:955: The following error occurred while executing this line:
/opt/RDPTools/Clustering/nbproject/build-impl.xml:300: Compile failed; see the compiler error output for details.

Total time: 4 seconds
make: *** [Clustering/dist/Clustering.jar] Error 1

**Comment by chaibenl** [comment]
nbetrapa,

Have you installed apache ant? Looks like all the errors can be traced back
to it.

Benli Chai
RDP Staff

**Comment by nbetrapa** [comment]
Hello Benli,

I do have apache installed. 

Here is the output when i type ant -version,

 ant -version
Apache Ant(TM) version 1.9.4 compiled on April 29 2014

**Comment by rdpstaffmsu** [comment]
Hi, nbetrapa,

I couldn't replicate the errors you encountered. This tool does not require
root installation. A wild guess is that root installation may cause some
conflicts at the system level. Try the entire clone process as a regular
user.

Benli

On Sun, May 1, 2016 at 6:01 PM, nbetrapa <notifications@github.com> wrote:

> Hello Benli,
>
> I do have apache installed.
>
> Here is the output when i type ant -version,
>
> ant -version
> Apache Ant(TM) version 1.9.4 compiled on April 29 2014
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/rdpstaff/classifier/issues/15#issuecomment-216075829>
>



-- 
RDP Staff
Ribosomal Database Project
Center for Microbial Ecology
Michigan State University
567 Wilson Rd. Room 2225 A
East Lansing, MI 48824
(517) 353-3842

**Comment by nbetrapa** [comment]
Hello Benli,

I really appreciate the follow up and help provided. I tried the entire clone process as a regular user, however the install still fails. 

I was wondering if this had to do anything with the following error while git update

github.com[0: 192.30.252.128]: errno=Connection timed out
fatal: unable to connect a socket (Connection timed out)
Clone of 'git://github.com/rdpstaff/TaxonomyTree' into submodule path 'TaxonomyTree' failed


Also, the only reason I am installing RDPTools is to be able to get access to the RDP Classifier 11 jar  executable file. Kindly help me on this.

**Comment by rdpstaffmsu** [comment]
Ok, it is a "better" error - only the time out setting is involved. Would
you run the following command prior to the procedure?:

 “git config --global url."https://".insteadOf git://”


Please let me know how it works for you.

Benli

On Tue, May 3, 2016 at 1:01 PM, nbetrapa <notifications@github.com> wrote:

> Hello Benli,
>
> I really appreciate the follow up and help provided. I tried the entire
> clone process as a regular user, however the install still fails.
>
> I was wondering if this had to do anything with the following error while
> git update
>
> github.com[0: 192.30.252.128]: errno=Connection timed out
> fatal: unable to connect a socket (Connection timed out)
> Clone of 'git://github.com/rdpstaff/TaxonomyTree' into submodule path
> 'TaxonomyTree' failed
>
> Also, the only reason I am installing RDPTools is to be able to get access
> to the RDP Classifier 11 jar executable file. Kindly help me on this.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/rdpstaff/classifier/issues/15#issuecomment-216596149>
>



-- 
RDP Staff
Ribosomal Database Project
Center for Microbial Ecology
Michigan State University
567 Wilson Rd. Room 2225 A
East Lansing, MI 48824
(517) 353-3842

**Comment by nbetrapa** [comment]
Hello Benli,

Thank you for the assistance, I followed your advice and was able to clone everything. However, the recent error message I received is with respect to the classifier which is the most important build I am looking for. Below is the error: 

BUILD SUCCESSFUL
Total time: 2 seconds
make: *** No rule to make target `classifier/nbproject/build-impl.xml', needed by `classifier/dist/classifier.jar'.  Stop.

I hope this is the last error I would face. I am really grateful for all the help you are providing.

**Comment by nbetrapa** [comment]
Hello Benli,

Kindly ignore the previous comment. After the error I got above, I ran the line,

git submodule update


That pulled all the remaining modules and was able to successfully install RDP tools. 


Thank you for all the help!
