### ISSUE TITLE
Online RDP classifier (http://rdp.cme.msu.edu/classifier/classifier.jsp.) cannot be opened

### ISSUE THREAD

**Issue by jingliu92** [rdpstaff/classifier#29]
Hi,
Thank you for reading this! I've been using the online RDP classifier for taxonomy classification, but I can't open the website recently. The error message is:

This site can’t be reached
http://rdp.cme.msu.edu/classifier/classifier.jsp is unreachable.
ERR_ADDRESS_UNREACHABLE

Thank you in advance for the help!

**Comment by gunturus** [comment]
The rdp group has retired as of 4/30/2023. We are currently not maintaining the website.

**Comment by jingliu92** [comment]
Thank you for the response! Is there any other alternative way to do this? Thank you!!!

**Comment by gunturus** [comment]
https://sourceforge.net/projects/rdp-classifier/

you can try installing the classifier using the link above. You would need Linux or macbook system for it.
