### ISSUE TITLE
merge-detail for fungal its

### ISSUE THREAD

**Issue by dbrami** [rdpstaff/classifier#7]
Hi I'm getting the following error:
```bash
cmd-> java -Xmx16g -jar /bio_bin/rdp_classifier_2.10.1/dist/classifier.jar merge-detail \
> -o combined_rdp.txt -h combined_hierarchy.txt -c 0.5 --gene fungalits_unite \
> S14MNOARP5.trimmed.noplant/S14MNOARP5.trimmed.noplant_UNITE_public_30.12.2014_UniVec.ovl.dusted.valid.rdp.tmp \
> S14MNOAEP5.trimmed.noplant/S14MNOAEP5.trimmed.noplant_UNITE_public_30.12.2014_UniVec.ovl.dusted.valid.rdp.tmp
Command Error: fungalits_unite is NOT valid, only allows 16srrna, fungallsu, fungalits_warcup and fungalits_unite
```
Any ideas why? The classification portion worked without issue.

**Comment by rdpstaffmsu** [comment]
Dear Daniel,

Would you send the two input files to us to test? Thank you.

Sincerely,

Benli Chai
RDP Staff

On Fri, Feb 27, 2015 at 2:15 PM, Daniel Brami <notifications@github.com>
wrote:

> Hi I'm getting the following error:
>
> cmd-> java -Xmx16g -jar /bio_bin/rdp_classifier_2.10.1/dist/classifier.jar merge-detail \> -o combined_rdp.txt -h combined_hierarchy.txt -c 0.5 --gene fungalits_unite \> S14MNOARP5.trimmed.noplant/S14MNOARP5.trimmed.noplant_UNITE_public_30.12.2014_UniVec.ovl.dusted.valid.rdp.tmp \> S14MNOAEP5.trimmed.noplant/S14MNOAEP5.trimmed.noplant_UNITE_public_30.12.2014_UniVec.ovl.dusted.valid.rdp.tmp
> Command Error: fungalits_unite is NOT valid, only allows 16srrna, fungallsu, fungalits_warcup and fungalits_unite
>
> Any ideas why?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rdpstaff/classifier/issues/7>.
>



-- 
RDP Staff
Ribosomal Database Project
Center for Microbial Ecology
Michigan State University
567 Wilson Rd. Room 2225 A
East Lansing, MI 48824
(517) 353-3842

**Comment by dbrami** [comment]
Hello Benli,
Forgive me but I can't figure out how to attach files to an issue if the files are not of the graphical type.
Please suggest the best method.

**Comment by dbrami** [comment]
Hi Benli,
Is there an email address I can send the files to?

**Comment by rdpstaffmsu** [comment]
Hi, Daniel,

Please send to rdpstaff@msu.edu. Thank you.

Benli

On Mon, Mar 2, 2015 at 1:26 PM, Daniel Brami <notifications@github.com>
wrote:

> Hi Benli,
> Is there an email address I can send the files to?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rdpstaff/classifier/issues/7#issuecomment-76770335>.
>



-- 
RDP Staff
Ribosomal Database Project
Center for Microbial Ecology
Michigan State University
567 Wilson Rd. Room 2225 A
East Lansing, MI 48824
(517) 353-3842

**Comment by dbrami** [comment]
Thank you for the email response.
I have cloned a copy of the classifier repo but the 'dist' and 'lib' folders are not part of this cloned repo.
I do not want to venture into assuming how to compile this properly. Any suggestions so that I may test again?

**Comment by rdpstaffmsu** [comment]
Hi, Daniel,

The best is to clone the entire RDPTools package (
https://github.com/rdpstaff/RDPTools) since the classifier has dependencies
on a couple other utilities. The procedure is:

After cloning this repository enter the commands:

## Initial Project Set Up
$ git submodule init
$ git submodule update

then type 'make'




Let me know there is a problem.



Benli



On Mon, Mar 2, 2015 at 5:19 PM, Daniel Brami <notifications@github.com>
wrote:

> Thank you for the email response.
> I have cloned a copy of the classifier repo but the 'dist' and 'lib'
> folders are not part of this cloned repo.
> I do not want to venture into assuming how to compile this properly. Any
> suggestions so that I may test again?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rdpstaff/classifier/issues/7#issuecomment-76839009>.
>



-- 
RDP Staff
Ribosomal Database Project
Center for Microbial Ecology
Michigan State University
567 Wilson Rd. Room 2225 A
East Lansing, MI 48824
(517) 353-3842

**Comment by dbrami** [comment]
Worked like a charm - thanks for the help!
